version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    container_name: postgres
    environment:
      - POSTGRES_USER=evil
      - POSTGRES_PASSWORD=affirm-clause-accurate
    volumes:
      - postgres:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 256M
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

volumes:
  postgres:
    driver: local
